/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Variable } from '../../models/variable';
import { VariableData } from '../../models/variable-data';

export interface CrearVariableVariablesPost$Params {
      body: VariableData
}

export function crearVariableVariablesPost(http: HttpClient, rootUrl: string, params: CrearVariableVariablesPost$Params, context?: HttpContext): Observable<StrictHttpResponse<Variable>> {
  const rb = new RequestBuilder(rootUrl, crearVariableVariablesPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Variable>;
    })
  );
}

crearVariableVariablesPost.PATH = '/variables/';
