/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface EliminarVariableVariablesVariableIdDelete$Params {
  variable_id: number;
}

export function eliminarVariableVariablesVariableIdDelete(http: HttpClient, rootUrl: string, params: EliminarVariableVariablesVariableIdDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<any>> {
  const rb = new RequestBuilder(rootUrl, eliminarVariableVariablesVariableIdDelete.PATH, 'delete');
  if (params) {
    rb.path('variable_id', params.variable_id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<any>;
    })
  );
}

eliminarVariableVariablesVariableIdDelete.PATH = '/variables/{variable_id}';
