/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PaginationDataScroringLogs } from '../../models/pagination-data-scroring-logs';

export interface ObtenerScoringLogsScoringLogsGet$Params {
  skip?: number;
  limit?: number;
  min_date?: string;
  max_date?: string;
}

export function obtenerScoringLogsScoringLogsGet(http: HttpClient, rootUrl: string, params?: ObtenerScoringLogsScoringLogsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<PaginationDataScroringLogs>> {
  const rb = new RequestBuilder(rootUrl, obtenerScoringLogsScoringLogsGet.PATH, 'get');
  if (params) {
    rb.query('skip', params.skip, {});
    rb.query('limit', params.limit, {});
    rb.query('min_date', params.min_date, {});
    rb.query('max_date', params.max_date, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PaginationDataScroringLogs>;
    })
  );
}

obtenerScoringLogsScoringLogsGet.PATH = '/scoring/logs/';
