/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Perfil } from '../../models/perfil';
import { PerfilPatch } from '../../models/perfil-patch';

export interface ParchearPerfilPerfilesPerfilIdPatch$Params {
  perfil_id: number;
      body: PerfilPatch
}

export function parchearPerfilPerfilesPerfilIdPatch(http: HttpClient, rootUrl: string, params: ParchearPerfilPerfilesPerfilIdPatch$Params, context?: HttpContext): Observable<StrictHttpResponse<Perfil>> {
  const rb = new RequestBuilder(rootUrl, parchearPerfilPerfilesPerfilIdPatch.PATH, 'patch');
  if (params) {
    rb.path('perfil_id', params.perfil_id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Perfil>;
    })
  );
}

parchearPerfilPerfilesPerfilIdPatch.PATH = '/perfiles/{perfil_id}';
