/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MarcaEspecialResponse } from '../../models/marca-especial-response';
import { MarcaEspecialUpdate } from '../../models/marca-especial-update';

export interface ActualizarMarcaEspecialEventosMarcasMarcaIdPatch$Params {
  marca_id: number;
      body: MarcaEspecialUpdate
}

export function actualizarMarcaEspecialEventosMarcasMarcaIdPatch(http: HttpClient, rootUrl: string, params: ActualizarMarcaEspecialEventosMarcasMarcaIdPatch$Params, context?: HttpContext): Observable<StrictHttpResponse<MarcaEspecialResponse>> {
  const rb = new RequestBuilder(rootUrl, actualizarMarcaEspecialEventosMarcasMarcaIdPatch.PATH, 'patch');
  if (params) {
    rb.path('marca_id', params.marca_id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<MarcaEspecialResponse>;
    })
  );
}

actualizarMarcaEspecialEventosMarcasMarcaIdPatch.PATH = '/eventos/marcas/{marca_id}';
