/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MarcaEspecialCreate } from '../../models/marca-especial-create';
import { MarcaEspecialResponse } from '../../models/marca-especial-response';

export interface CrearMarcaEspecialEventosMarcasPost$Params {
      body: MarcaEspecialCreate
}

export function crearMarcaEspecialEventosMarcasPost(http: HttpClient, rootUrl: string, params: CrearMarcaEspecialEventosMarcasPost$Params, context?: HttpContext): Observable<StrictHttpResponse<MarcaEspecialResponse>> {
  const rb = new RequestBuilder(rootUrl, crearMarcaEspecialEventosMarcasPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<MarcaEspecialResponse>;
    })
  );
}

crearMarcaEspecialEventosMarcasPost.PATH = '/eventos/marcas';
