/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface EliminarMarcaEspecialEventosMarcasMarcaIdDelete$Params {
  marca_id: number;
}

export function eliminarMarcaEspecialEventosMarcasMarcaIdDelete(http: HttpClient, rootUrl: string, params: EliminarMarcaEspecialEventosMarcasMarcaIdDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, eliminarMarcaEspecialEventosMarcasMarcaIdDelete.PATH, 'delete');
  if (params) {
    rb.path('marca_id', params.marca_id, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

eliminarMarcaEspecialEventosMarcasMarcaIdDelete.PATH = '/eventos/marcas/{marca_id}';
