/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MarcaEspecialResponse } from '../../models/marca-especial-response';

export interface ListarMarcasEspecialesEventosMarcasGet$Params {
  institucion_id?: (number | null);
}

export function listarMarcasEspecialesEventosMarcasGet(http: HttpClient, rootUrl: string, params?: ListarMarcasEspecialesEventosMarcasGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<MarcaEspecialResponse>>> {
  const rb = new RequestBuilder(rootUrl, listarMarcasEspecialesEventosMarcasGet.PATH, 'get');
  if (params) {
    rb.query('institucion_id', params.institucion_id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<MarcaEspecialResponse>>;
    })
  );
}

listarMarcasEspecialesEventosMarcasGet.PATH = '/eventos/marcas';
