/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { EventoDemandaResponse } from '../../models/evento-demanda-response';

export interface ListarEventosDemandaEventosDemandaGet$Params {
  institucion_id?: (number | null);
  estado?: (string | null);
}

export function listarEventosDemandaEventosDemandaGet(http: HttpClient, rootUrl: string, params?: ListarEventosDemandaEventosDemandaGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<EventoDemandaResponse>>> {
  const rb = new RequestBuilder(rootUrl, listarEventosDemandaEventosDemandaGet.PATH, 'get');
  if (params) {
    rb.query('institucion_id', params.institucion_id, {});
    rb.query('estado', params.estado, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<EventoDemandaResponse>>;
    })
  );
}

listarEventosDemandaEventosDemandaGet.PATH = '/eventos/demanda';
