/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { EventoDemandaResponse } from '../../models/evento-demanda-response';

export interface ObtenerEventoDemandaEventosDemandaEventoIdGet$Params {
  evento_id: number;
}

export function obtenerEventoDemandaEventosDemandaEventoIdGet(http: HttpClient, rootUrl: string, params: ObtenerEventoDemandaEventosDemandaEventoIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<EventoDemandaResponse>> {
  const rb = new RequestBuilder(rootUrl, obtenerEventoDemandaEventosDemandaEventoIdGet.PATH, 'get');
  if (params) {
    rb.path('evento_id', params.evento_id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<EventoDemandaResponse>;
    })
  );
}

obtenerEventoDemandaEventosDemandaEventoIdGet.PATH = '/eventos/demanda/{evento_id}';
