/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseListPagoResponse } from '../../models/api-response-list-pago-response';

export interface ListarPagosRegistradosPorAlumno$Params {
  alumnoId: number;
}

export function listarPagosRegistradosPorAlumno(http: HttpClient, rootUrl: string, params: ListarPagosRegistradosPorAlumno$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseListPagoResponse>> {
  const rb = new RequestBuilder(rootUrl, listarPagosRegistradosPorAlumno.PATH, 'get');
  if (params) {
    rb.path('alumnoId', params.alumnoId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseListPagoResponse>;
    })
  );
}

listarPagosRegistradosPorAlumno.PATH = '/pagos/alumno/{alumnoId}';
