/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseListPagoResponse } from '../../models/api-response-list-pago-response';

export interface ListarPagosRegistradosPorCuota$Params {
  cuotaId: number;
}

export function listarPagosRegistradosPorCuota(http: HttpClient, rootUrl: string, params: ListarPagosRegistradosPorCuota$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseListPagoResponse>> {
  const rb = new RequestBuilder(rootUrl, listarPagosRegistradosPorCuota.PATH, 'get');
  if (params) {
    rb.path('cuotaId', params.cuotaId, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseListPagoResponse>;
    })
  );
}

listarPagosRegistradosPorCuota.PATH = '/pagos/cuota/{cuotaId}';
