/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponsePagoResponse } from '../../models/api-response-pago-response';
import { PagoRequest } from '../../models/pago-request';

export interface Registrar2$Params {
      body: PagoRequest
}

export function registrar2(http: HttpClient, rootUrl: string, params: Registrar2$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponsePagoResponse>> {
  const rb = new RequestBuilder(rootUrl, registrar2.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponsePagoResponse>;
    })
  );
}

registrar2.PATH = '/pagos';
