/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseString } from '../../models/api-response-string';
import { CuentaRequest } from '../../models/cuenta-request';

export interface ActualizarMontoYSaldoDeCuenta$Params {
  id_estado_cuenta: number;
      body: CuentaRequest
}

export function actualizarMontoYSaldoDeCuenta(http: HttpClient, rootUrl: string, params: ActualizarMontoYSaldoDeCuenta$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseString>> {
  const rb = new RequestBuilder(rootUrl, actualizarMontoYSaldoDeCuenta.PATH, 'put');
  if (params) {
    rb.path('id_estado_cuenta', params.id_estado_cuenta, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseString>;
    })
  );
}

actualizarMontoYSaldoDeCuenta.PATH = '/estado-cuenta/cambiar-monto/{id_estado_cuenta}';
