/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseListCuentaResponse } from '../../models/api-response-list-cuenta-response';

export interface EstadoCuentaAlumnoCronograma$Params {
  id_alumno: number;
  id_cronograma: number;
}

export function estadoCuentaAlumnoCronograma(http: HttpClient, rootUrl: string, params: EstadoCuentaAlumnoCronograma$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseListCuentaResponse>> {
  const rb = new RequestBuilder(rootUrl, estadoCuentaAlumnoCronograma.PATH, 'get');
  if (params) {
    rb.path('id_alumno', params.id_alumno, {});
    rb.path('id_cronograma', params.id_cronograma, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseListCuentaResponse>;
    })
  );
}

estadoCuentaAlumnoCronograma.PATH = '/estado-cuenta/matricula/alumno/{id_alumno}/cronograma/{id_cronograma}';
