/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseUsuarioResponse } from '../../models/api-response-usuario-response';

export interface ObtenerPerfilUsuario$Params {
}

export function obtenerPerfilUsuario(http: HttpClient, rootUrl: string, params?: ObtenerPerfilUsuario$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseUsuarioResponse>> {
  const rb = new RequestBuilder(rootUrl, obtenerPerfilUsuario.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseUsuarioResponse>;
    })
  );
}

obtenerPerfilUsuario.PATH = '/usuario/perfil';
