/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseUsuarioResponse } from '../../models/api-response-usuario-response';

export interface ObtenerUsuarioPorId$Params {
  id: number;
}

export function obtenerUsuarioPorId(http: HttpClient, rootUrl: string, params: ObtenerUsuarioPorId$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseUsuarioResponse>> {
  const rb = new RequestBuilder(rootUrl, obtenerUsuarioPorId.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseUsuarioResponse>;
    })
  );
}

obtenerUsuarioPorId.PATH = '/usuario/{id}';
