/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PlantillaMensaje } from '../../models/plantilla-mensaje';
import { PlantillaMensajeData } from '../../models/plantilla-mensaje-data';

export interface CrearPlantillaPlantillasPost$Params {
      body: PlantillaMensajeData
}

export function crearPlantillaPlantillasPost(http: HttpClient, rootUrl: string, params: CrearPlantillaPlantillasPost$Params, context?: HttpContext): Observable<StrictHttpResponse<PlantillaMensaje>> {
  const rb = new RequestBuilder(rootUrl, crearPlantillaPlantillasPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PlantillaMensaje>;
    })
  );
}

crearPlantillaPlantillasPost.PATH = '/plantillas/';
