/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Notificacion } from '../../models/notificacion';
import { NotificacionData } from '../../models/notificacion-data';

export interface CrearNotificacionNotificacionesPost$Params {
      body: NotificacionData
}

export function crearNotificacionNotificacionesPost(http: HttpClient, rootUrl: string, params: CrearNotificacionNotificacionesPost$Params, context?: HttpContext): Observable<StrictHttpResponse<Notificacion>> {
  const rb = new RequestBuilder(rootUrl, crearNotificacionNotificacionesPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Notificacion>;
    })
  );
}

crearNotificacionNotificacionesPost.PATH = '/notificaciones/';
