/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Campania } from '../../models/campania';
import { CampaniaData } from '../../models/campania-data';

export interface CrearCampaniaCampaniasPost$Params {
      body: CampaniaData
}

export function crearCampaniaCampaniasPost(http: HttpClient, rootUrl: string, params: CrearCampaniaCampaniasPost$Params, context?: HttpContext): Observable<StrictHttpResponse<Campania>> {
  const rb = new RequestBuilder(rootUrl, crearCampaniaCampaniasPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Campania>;
    })
  );
}

crearCampaniaCampaniasPost.PATH = '/campanias/';
