/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface EliminarNotificacionNotificacionesNotificacionIdDelete$Params {
  notificacion_id: number;
}

export function eliminarNotificacionNotificacionesNotificacionIdDelete(http: HttpClient, rootUrl: string, params: EliminarNotificacionNotificacionesNotificacionIdDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<any>> {
  const rb = new RequestBuilder(rootUrl, eliminarNotificacionNotificacionesNotificacionIdDelete.PATH, 'delete');
  if (params) {
    rb.path('notificacion_id', params.notificacion_id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<any>;
    })
  );
}

eliminarNotificacionNotificacionesNotificacionIdDelete.PATH = '/notificaciones/{notificacion_id}';
