/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Campania } from '../../models/campania';
import { CampaniaPatch } from '../../models/campania-patch';

export interface ParchearCampaniaCampaniasCampaniaIdPatch$Params {
  campania_id: number;
      body: CampaniaPatch
}

export function parchearCampaniaCampaniasCampaniaIdPatch(http: HttpClient, rootUrl: string, params: ParchearCampaniaCampaniasCampaniaIdPatch$Params, context?: HttpContext): Observable<StrictHttpResponse<Campania>> {
  const rb = new RequestBuilder(rootUrl, parchearCampaniaCampaniasCampaniaIdPatch.PATH, 'patch');
  if (params) {
    rb.path('campania_id', params.campania_id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Campania>;
    })
  );
}

parchearCampaniaCampaniasCampaniaIdPatch.PATH = '/campanias/{campania_id}';
