/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Notificacion } from '../../models/notificacion';
import { NotificacionPatch } from '../../models/notificacion-patch';

export interface ParchearNotificacionNotificacionesNotificacionIdPatch$Params {
  notificacion_id: number;
      body: NotificacionPatch
}

export function parchearNotificacionNotificacionesNotificacionIdPatch(http: HttpClient, rootUrl: string, params: ParchearNotificacionNotificacionesNotificacionIdPatch$Params, context?: HttpContext): Observable<StrictHttpResponse<Notificacion>> {
  const rb = new RequestBuilder(rootUrl, parchearNotificacionNotificacionesNotificacionIdPatch.PATH, 'patch');
  if (params) {
    rb.path('notificacion_id', params.notificacion_id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Notificacion>;
    })
  );
}

parchearNotificacionNotificacionesNotificacionIdPatch.PATH = '/notificaciones/{notificacion_id}';
