/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PlantillaMensaje } from '../../models/plantilla-mensaje';
import { PlantillaMensajePatch } from '../../models/plantilla-mensaje-patch';

export interface ParchearPlantillaPlantillasPlantillaIdPatch$Params {
  plantilla_id: number;
      body: PlantillaMensajePatch
}

export function parchearPlantillaPlantillasPlantillaIdPatch(http: HttpClient, rootUrl: string, params: ParchearPlantillaPlantillasPlantillaIdPatch$Params, context?: HttpContext): Observable<StrictHttpResponse<PlantillaMensaje>> {
  const rb = new RequestBuilder(rootUrl, parchearPlantillaPlantillasPlantillaIdPatch.PATH, 'patch');
  if (params) {
    rb.path('plantilla_id', params.plantilla_id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PlantillaMensaje>;
    })
  );
}

parchearPlantillaPlantillasPlantillaIdPatch.PATH = '/plantillas/{plantilla_id}';
