/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AlumnoUpdateRequest } from '../../models/alumno-update-request';
import { ApiResponseString } from '../../models/api-response-string';

export interface ActualizarDatosGeneralesDelAlumno$Params {
  id: number;
      body: AlumnoUpdateRequest
}

export function actualizarDatosGeneralesDelAlumno(http: HttpClient, rootUrl: string, params: ActualizarDatosGeneralesDelAlumno$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseString>> {
  const rb = new RequestBuilder(rootUrl, actualizarDatosGeneralesDelAlumno.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseString>;
    })
  );
}

actualizarDatosGeneralesDelAlumno.PATH = '/student/{id}';
