/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseString } from '../../models/api-response-string';

export interface ActualizarDocumentoIdentidadDelAlumno$Params {
  id: number;
  dni: string;
}

export function actualizarDocumentoIdentidadDelAlumno(http: HttpClient, rootUrl: string, params: ActualizarDocumentoIdentidadDelAlumno$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseString>> {
  const rb = new RequestBuilder(rootUrl, actualizarDocumentoIdentidadDelAlumno.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.query('dni', params.dni, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseString>;
    })
  );
}

actualizarDocumentoIdentidadDelAlumno.PATH = '/student/dni/{id}';
