/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseAlumnoEstadoCuentaResponse } from '../../models/api-response-alumno-estado-cuenta-response';

export interface ObtenerEstadoCuenta$Params {
  id: number;
}

export function obtenerEstadoCuenta(http: HttpClient, rootUrl: string, params: ObtenerEstadoCuenta$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseAlumnoEstadoCuentaResponse>> {
  const rb = new RequestBuilder(rootUrl, obtenerEstadoCuenta.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseAlumnoEstadoCuentaResponse>;
    })
  );
}

obtenerEstadoCuenta.PATH = '/student/{id}/statement';
