/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseAccessTokenResponse } from '../../models/api-response-access-token-response';

export interface RenovarTokenDeAcceso$Params {
}

export function renovarTokenDeAcceso(http: HttpClient, rootUrl: string, params?: RenovarTokenDeAcceso$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseAccessTokenResponse>> {
  const rb = new RequestBuilder(rootUrl, renovarTokenDeAcceso.PATH, 'post');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseAccessTokenResponse>;
    })
  );
}

renovarTokenDeAcceso.PATH = '/auth/refresh';
