/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseListCuotaResponse } from '../../models/api-response-list-cuota-response';

export interface ListarCuotasPorCronograma$Params {
  id: number;
}

export function listarCuotasPorCronograma(http: HttpClient, rootUrl: string, params: ListarCuotasPorCronograma$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseListCuotaResponse>> {
  const rb = new RequestBuilder(rootUrl, listarCuotasPorCronograma.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseListCuotaResponse>;
    })
  );
}

listarCuotasPorCronograma.PATH = '/cronograma/{id}/cuotas';
