/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponsePageCronogramaResponse } from '../../models/api-response-page-cronograma-response';

export interface ListarCronogramasConFiltros$Params {

/**
 * Filtrar por año lectivo
 */
  anioLectivo?: string;

/**
 * Filtrar por nivel educativo
 */
  nivelEducativo?: string;

/**
 * Filtrar por estado activo
 */
  activo?: boolean;

/**
 * Número de página
 */
  page?: number;

/**
 * Cantidad de registros por página
 */
  size?: number;

/**
 * Configuración de ordenamiento en formato JSON
 */
  sort?: string;
}

export function listarCronogramasConFiltros(http: HttpClient, rootUrl: string, params?: ListarCronogramasConFiltros$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponsePageCronogramaResponse>> {
  const rb = new RequestBuilder(rootUrl, listarCronogramasConFiltros.PATH, 'get');
  if (params) {
    rb.query('anioLectivo', params.anioLectivo, {});
    rb.query('nivelEducativo', params.nivelEducativo, {});
    rb.query('activo', params.activo, {});
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
    rb.query('sort', params.sort, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponsePageCronogramaResponse>;
    })
  );
}

listarCronogramasConFiltros.PATH = '/cronograma';
