/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseCronogramaDetalleResponse } from '../../models/api-response-cronograma-detalle-response';

export interface ObtenerCronogramaConCuotas$Params {
  id: number;
}

export function obtenerCronogramaConCuotas(http: HttpClient, rootUrl: string, params: ObtenerCronogramaConCuotas$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseCronogramaDetalleResponse>> {
  const rb = new RequestBuilder(rootUrl, obtenerCronogramaConCuotas.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseCronogramaDetalleResponse>;
    })
  );
}

obtenerCronogramaConCuotas.PATH = '/cronograma/{id}';
