/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseNotificacionConfigracionResponse } from '../../models/api-response-notificacion-configracion-response';
import { NotificacionConfigracionRegister } from '../../models/notificacion-configracion-register';

export interface Guardar$Params {
      body: NotificacionConfigracionRegister
}

export function guardar(http: HttpClient, rootUrl: string, params: Guardar$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseNotificacionConfigracionResponse>> {
  const rb = new RequestBuilder(rootUrl, guardar.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseNotificacionConfigracionResponse>;
    })
  );
}

guardar.PATH = '/notificacion-configuracion';
