/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseNotificacionConfigracionResponse } from '../../models/api-response-notificacion-configracion-response';

export interface Obtener$Params {
  code: string;
  medioEnvio: 'SMS' | 'WHATSAPP' | 'IVR' | 'EMAIL';
}

export function obtener(http: HttpClient, rootUrl: string, params: Obtener$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseNotificacionConfigracionResponse>> {
  const rb = new RequestBuilder(rootUrl, obtener.PATH, 'get');
  if (params) {
    rb.path('code', params.code, {});
    rb.path('medioEnvio', params.medioEnvio, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseNotificacionConfigracionResponse>;
    })
  );
}

obtener.PATH = '/notificacion-configuracion/institucion/{code}/medio/{medioEnvio}';
