/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseBoolean } from '../../models/api-response-boolean';

export interface VerificarExistenciaDeConfiguracion$Params {
  code: string;
  medioEnvio: 'SMS' | 'WHATSAPP' | 'EMAIL';
}

export function verificarExistenciaDeConfiguracion(http: HttpClient, rootUrl: string, params: VerificarExistenciaDeConfiguracion$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseBoolean>> {
  const rb = new RequestBuilder(rootUrl, verificarExistenciaDeConfiguracion.PATH, 'get');
  if (params) {
    rb.path('code', params.code, {});
    rb.path('medioEnvio', params.medioEnvio, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseBoolean>;
    })
  );
}

verificarExistenciaDeConfiguracion.PATH = '/notificacion-configuracion/existe/{code}/medio/{medioEnvio}';
