/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PaginationDataVariables } from '../../models/pagination-data-variables';

export interface ListarVariablesVariablesGet$Params {
  skip?: number;
  limit?: number;
}

export function listarVariablesVariablesGet(http: HttpClient, rootUrl: string, params?: ListarVariablesVariablesGet$Params, context?: HttpContext): Observable<StrictHttpResponse<PaginationDataVariables>> {
  const rb = new RequestBuilder(rootUrl, listarVariablesVariablesGet.PATH, 'get');
  if (params) {
    rb.query('skip', params.skip, {});
    rb.query('limit', params.limit, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PaginationDataVariables>;
    })
  );
}

listarVariablesVariablesGet.PATH = '/variables/';
