/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ReporteFinancieroFiltros } from '../../models/reporte-financiero-filtros';
import { ReporteFinancieroResponse } from '../../models/reporte-financiero-response';

export interface GenerarReporteFinancieroReportesFinancieroPost$Params {
      body: ReporteFinancieroFiltros
}

export function generarReporteFinancieroReportesFinancieroPost(http: HttpClient, rootUrl: string, params: GenerarReporteFinancieroReportesFinancieroPost$Params, context?: HttpContext): Observable<StrictHttpResponse<ReporteFinancieroResponse>> {
  const rb = new RequestBuilder(rootUrl, generarReporteFinancieroReportesFinancieroPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ReporteFinancieroResponse>;
    })
  );
}

generarReporteFinancieroReportesFinancieroPost.PATH = '/reportes/financiero';
