/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CompromisoExoneracionResponse } from '../../models/compromiso-exoneracion-response';
import { CompromisoExoneracionUpdate } from '../../models/compromiso-exoneracion-update';

export interface ActualizarCompromisoCompromisosCompromisoIdPatch$Params {
  compromiso_id: number;
      body: CompromisoExoneracionUpdate
}

export function actualizarCompromisoCompromisosCompromisoIdPatch(http: HttpClient, rootUrl: string, params: ActualizarCompromisoCompromisosCompromisoIdPatch$Params, context?: HttpContext): Observable<StrictHttpResponse<CompromisoExoneracionResponse>> {
  const rb = new RequestBuilder(rootUrl, actualizarCompromisoCompromisosCompromisoIdPatch.PATH, 'patch');
  if (params) {
    rb.path('compromiso_id', params.compromiso_id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CompromisoExoneracionResponse>;
    })
  );
}

actualizarCompromisoCompromisosCompromisoIdPatch.PATH = '/compromisos/{compromiso_id}';
