/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface EliminarCompromisoCompromisosCompromisoIdDelete$Params {
  compromiso_id: number;
}

export function eliminarCompromisoCompromisosCompromisoIdDelete(http: HttpClient, rootUrl: string, params: EliminarCompromisoCompromisosCompromisoIdDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, eliminarCompromisoCompromisosCompromisoIdDelete.PATH, 'delete');
  if (params) {
    rb.path('compromiso_id', params.compromiso_id, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

eliminarCompromisoCompromisosCompromisoIdDelete.PATH = '/compromisos/{compromiso_id}';
