/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CompromisoExoneracionResponse } from '../../models/compromiso-exoneracion-response';

export interface ListarCompromisosCompromisosGet$Params {
  cuenta_id?: (number | null);
  tipo?: (string | null);
  estado?: (string | null);
}

export function listarCompromisosCompromisosGet(http: HttpClient, rootUrl: string, params?: ListarCompromisosCompromisosGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<CompromisoExoneracionResponse>>> {
  const rb = new RequestBuilder(rootUrl, listarCompromisosCompromisosGet.PATH, 'get');
  if (params) {
    rb.query('cuenta_id', params.cuenta_id, {});
    rb.query('tipo', params.tipo, {});
    rb.query('estado', params.estado, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<CompromisoExoneracionResponse>>;
    })
  );
}

listarCompromisosCompromisosGet.PATH = '/compromisos';
