/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CompromisoExoneracionResponse } from '../../models/compromiso-exoneracion-response';

export interface ObtenerCompromisoCompromisosCompromisoIdGet$Params {
  compromiso_id: number;
}

export function obtenerCompromisoCompromisosCompromisoIdGet(http: HttpClient, rootUrl: string, params: ObtenerCompromisoCompromisosCompromisoIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<CompromisoExoneracionResponse>> {
  const rb = new RequestBuilder(rootUrl, obtenerCompromisoCompromisosCompromisoIdGet.PATH, 'get');
  if (params) {
    rb.path('compromiso_id', params.compromiso_id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CompromisoExoneracionResponse>;
    })
  );
}

obtenerCompromisoCompromisosCompromisoIdGet.PATH = '/compromisos/{compromiso_id}';
