/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CompromisoExoneracionCreate } from '../../models/compromiso-exoneracion-create';
import { CompromisoExoneracionResponse } from '../../models/compromiso-exoneracion-response';

export interface RegistrarCompromisoCompromisosPost$Params {
      body: CompromisoExoneracionCreate
}

export function registrarCompromisoCompromisosPost(http: HttpClient, rootUrl: string, params: RegistrarCompromisoCompromisosPost$Params, context?: HttpContext): Observable<StrictHttpResponse<CompromisoExoneracionResponse>> {
  const rb = new RequestBuilder(rootUrl, registrarCompromisoCompromisosPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CompromisoExoneracionResponse>;
    })
  );
}

registrarCompromisoCompromisosPost.PATH = '/compromisos';
