/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ConfirmarInstitucionRequest } from '../../models/confirmar-institucion-request';

export interface ConfirmarInstitucionAuthInstitucionesConfirmarPost$Params {
      body: ConfirmarInstitucionRequest
}

export function confirmarInstitucionAuthInstitucionesConfirmarPost(http: HttpClient, rootUrl: string, params: ConfirmarInstitucionAuthInstitucionesConfirmarPost$Params, context?: HttpContext): Observable<StrictHttpResponse<{
[key: string]: any;
}>> {
  const rb = new RequestBuilder(rootUrl, confirmarInstitucionAuthInstitucionesConfirmarPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      [key: string]: any;
      }>;
    })
  );
}

confirmarInstitucionAuthInstitucionesConfirmarPost.PATH = '/auth/instituciones/confirmar';
