/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseListNotificacionResponse } from '../../models/api-response-list-notificacion-response';

export interface ListarPorCuota1$Params {
  cuotaId: number;
}

export function listarPorCuota1(http: HttpClient, rootUrl: string, params: ListarPorCuota1$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseListNotificacionResponse>> {
  const rb = new RequestBuilder(rootUrl, listarPorCuota1.PATH, 'get');
  if (params) {
    rb.path('cuotaId', params.cuotaId, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseListNotificacionResponse>;
    })
  );
}

listarPorCuota1.PATH = '/notificaciones/cuota/{cuotaId}';
