/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseListNotificationScenarioResponse } from '../../models/api-response-list-notification-scenario-response';

export interface ListarEscenarios$Params {
}

export function listarEscenarios(http: HttpClient, rootUrl: string, params?: ListarEscenarios$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseListNotificationScenarioResponse>> {
  const rb = new RequestBuilder(rootUrl, listarEscenarios.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseListNotificationScenarioResponse>;
    })
  );
}

listarEscenarios.PATH = '/notification-scenarios';
