/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AlumnoUpdateRequest {
  direccion?: string;
  grado?: string;
  nivel?: string;
  nombreCompleto?: string;
  seccion?: string;
}
