/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MatriculaEstadoCuenta } from '../models/matricula-estado-cuenta';
export interface AlumnoEstadoCuentaResponse {
  alumnoId?: number;
  matriculas?: Array<MatriculaEstadoCuenta>;
  morosidad?: number;
  nombreCompleto?: string;
  totalPagado?: number;
  totalPendiente?: number;
}
