/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { NotificacionResponse } from '../models/notificacion-response';
export interface ApiResponseListNotificacionResponse {
  data?: Array<NotificacionResponse>;
  message?: string;
  success?: boolean;
}
