/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PageInstitutionResponse } from '../models/page-institution-response';
export interface ApiResponsePageInstitutionResponse {
  data?: PageInstitutionResponse;
  message?: string;
  success?: boolean;
}
