/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { NotificationScenarioResponse } from '../models/notification-scenario-response';
export interface ApiResponseListNotificationScenarioResponse {
  data?: Array<NotificationScenarioResponse>;
  message?: string;
  success?: boolean;
}
