/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { NotificationScenarioResponse } from '../models/notification-scenario-response';
export interface ApiResponseNotificationScenarioResponse {
  data?: NotificationScenarioResponse;
  message?: string;
  success?: boolean;
}
