/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AlumnoEstadoCuentaResponse } from '../models/alumno-estado-cuenta-response';
export interface ApiResponseAlumnoEstadoCuentaResponse {
  data?: AlumnoEstadoCuentaResponse;
  message?: string;
  success?: boolean;
}
