/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PageUsuarioResponse } from '../models/page-usuario-response';
export interface ApiResponsePageUsuarioResponse {
  data?: PageUsuarioResponse;
  message?: string;
  success?: boolean;
}
