/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CronogramaDetalleResponse } from '../models/cronograma-detalle-response';
export interface ApiResponseCronogramaDetalleResponse {
  data?: CronogramaDetalleResponse;
  message?: string;
  success?: boolean;
}
