/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AccessTokenResponse } from '../models/access-token-response';
export interface ApiResponseAccessTokenResponse {
  data?: AccessTokenResponse;
  message?: string;
  success?: boolean;
}
