/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PageCuentaResponse } from '../models/page-cuenta-response';
export interface ApiResponsePageCuentaResponse {
  data?: PageCuentaResponse;
  message?: string;
  success?: boolean;
}
