/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UsuarioResponse } from '../models/usuario-response';
export interface ApiResponseUsuarioResponse {
  data?: UsuarioResponse;
  message?: string;
  success?: boolean;
}
