/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { OtpChallengeResponse } from '../models/otp-challenge-response';
export interface ApiResponseOtpChallengeResponse {
  data?: OtpChallengeResponse;
  message?: string;
  success?: boolean;
}
