/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { InstitutionResponse } from '../models/institution-response';
export interface ApiResponseInstitutionResponse {
  data?: InstitutionResponse;
  message?: string;
  success?: boolean;
}
