/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PasarelaPagoResponse } from '../models/pasarela-pago-response';
export interface ApiResponsePasarelaPagoResponse {
  data?: PasarelaPagoResponse;
  message?: string;
  success?: boolean;
}
