/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CuentaResponse } from '../models/cuenta-response';
export interface ApiResponseListCuentaResponse {
  data?: Array<CuentaResponse>;
  message?: string;
  success?: boolean;
}
