/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PageCronogramaResponse } from '../models/page-cronograma-response';
export interface ApiResponsePageCronogramaResponse {
  data?: PageCronogramaResponse;
  message?: string;
  success?: boolean;
}
