/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PageAlumnoResponse } from '../models/page-alumno-response';
export interface ApiResponsePageAlumnoResponse {
  data?: PageAlumnoResponse;
  message?: string;
  success?: boolean;
}
