/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PagoResponse } from '../models/pago-response';
export interface ApiResponseListPagoResponse {
  data?: Array<PagoResponse>;
  message?: string;
  success?: boolean;
}
