/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PlanActionsResponse } from '../models/plan-actions-response';
export interface ApiResponsePlanActionsResponse {
  data?: PlanActionsResponse;
  message?: string;
  success?: boolean;
}
