/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CuotaResponse } from '../models/cuota-response';
export interface ApiResponseListCuotaResponse {
  data?: Array<CuotaResponse>;
  message?: string;
  success?: boolean;
}
