/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CuotaResponse } from '../models/cuota-response';
export interface CronogramaDetalleResponse {
  activo?: boolean;
  anioLectivo?: number;
  cuotas?: Array<CuotaResponse>;
  id?: number;
  interesMoraCuota?: number;
  nivelEducativo?: 'PRIMARIA' | 'SECUNDARIA' | 'INICIAL';
}
