/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface InstitutionRequestRegister {
  address?: string;
  code?: string;
  email?: string;
  name?: string;
  phoneNumber?: string;
}
