/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface InstitutionUpdateLdpa {
  ldapBaseDn?: string;
  ldapHost?: string;
  ldapPassword?: string;
  ldapPort?: string;
  ldapUserDn?: string;
  useLdap?: boolean;
}
