/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface LoginRequest {
  contrasena?: string;
  institutionCode?: string;
  nombreUsuario?: string;
  recordarDispositivo?: boolean;
}
