/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface NotificationWebhookRequest {
  descripcion?: string;
  estado?: string;
  externalId?: string;
  fechaEvento?: string;
  notificationId?: number;
}
