/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface NotificationScenarioSummary {
  active?: boolean;
  description?: string;
  id?: number;
  messageTemplate?: string;
  relativeDays?: number;
  subjectTemplate?: string;
}
