/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface NotificacionConfigracionResponse {
  activo?: boolean;
  asunto?: string;
  diadDelMes?: number;
  frecuencia?: string;
  horaEnvio?: string;
  id?: number;
  institutionCode?: string;
  medioEnvio?: 'SMS' | 'WHATSAPP' | 'EMAIL';
  mensaje?: string;
}
