/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface NotificacionResponse {
  asunto?: string;
  configuracionId?: number;
  cuotaId?: number;
  frecuencia?: string;
  horaEnvio?: string;
  id?: number;
  medioEnvio?: 'SMS' | 'WHATSAPP' | 'EMAIL';
  mensaje?: string;
  numeroCuota?: number;
}
