/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface NotificationScenarioRequest {
  active?: boolean;
  description?: string;
  messageTemplate?: string;
  relativeDays?: number;
  subjectTemplate?: string;
}
