/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PagoRequest {
  fechaPago?: string;
  idAlumno?: number;
  idCuota?: number;
  idMatricula?: number;
  idUsuario?: number;
  metodoPago?: 'EFECTIVO' | 'TARJETA_DEBITO' | 'TARJETA_CREDITO' | 'TRANSFERENCIA_BANCARIA' | 'YAPE' | 'PLIN';
  montoPagado?: number;
  numeroOperacion?: string;
  observaciones?: string;
  pasarela?: 'Culqui';
}
