/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PasarelaPagoResponse {
  activo?: boolean;
  apiPublicKey?: string;
  apiSecret?: string;
  id?: number;
  institutionCode?: string;
  tipo?: 'Culqui';
  urlBase?: string;
  urlWebhook?: string;
}
