/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PasarelaPagoRegister {
  activo?: boolean;
  apiPublicKey?: string;
  apiSecret?: string;
  institutionCode?: string;
  tipo?: 'Culqui';
  urlBase?: string;
  urlWebhook?: string;
}
