/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PlanActionsResponse {
  accionesDestacadas?: Array<string>;
  canalesDisponibles?: Array<string>;
  escenariosDeEnvio?: number;
  personalizacionPorEscenario?: boolean;
  plan?: 'BASICO' | 'AVANZADO' | 'PREMIUM';
}
