/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponsePasarelaPagoResponse } from '../../models/api-response-pasarela-pago-response';
import { PasarelaPagoRegister } from '../../models/pasarela-pago-register';

export interface ActualizarConfiguracionDePasarela$Params {
  code: string;
      body: PasarelaPagoRegister
}

export function actualizarConfiguracionDePasarela(http: HttpClient, rootUrl: string, params: ActualizarConfiguracionDePasarela$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponsePasarelaPagoResponse>> {
  const rb = new RequestBuilder(rootUrl, actualizarConfiguracionDePasarela.PATH, 'put');
  if (params) {
    rb.path('code', params.code, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponsePasarelaPagoResponse>;
    })
  );
}

actualizarConfiguracionDePasarela.PATH = '/pasarela-pago/{code}';
