/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponsePasarelaPagoResponse } from '../../models/api-response-pasarela-pago-response';

export interface ObtenerConfiguracionPorCodigoInstitucion$Params {
  code: string;
}

export function obtenerConfiguracionPorCodigoInstitucion(http: HttpClient, rootUrl: string, params: ObtenerConfiguracionPorCodigoInstitucion$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponsePasarelaPagoResponse>> {
  const rb = new RequestBuilder(rootUrl, obtenerConfiguracionPorCodigoInstitucion.PATH, 'get');
  if (params) {
    rb.path('code', params.code, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponsePasarelaPagoResponse>;
    })
  );
}

obtenerConfiguracionPorCodigoInstitucion.PATH = '/pasarela-pago/institucion/{code}';
