/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Cronograma } from '../../models/cronograma';
import { CronogramaData } from '../../models/cronograma-data';

export interface ActualizarCronogramaCronogramasCronogramaIdPut$Params {
  cronograma_id: number;
      body: CronogramaData
}

export function actualizarCronogramaCronogramasCronogramaIdPut(http: HttpClient, rootUrl: string, params: ActualizarCronogramaCronogramasCronogramaIdPut$Params, context?: HttpContext): Observable<StrictHttpResponse<Cronograma>> {
  const rb = new RequestBuilder(rootUrl, actualizarCronogramaCronogramasCronogramaIdPut.PATH, 'put');
  if (params) {
    rb.path('cronograma_id', params.cronograma_id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Cronograma>;
    })
  );
}

actualizarCronogramaCronogramasCronogramaIdPut.PATH = '/cronogramas/{cronograma_id}';
