/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ResponsablePagoDispositivo } from '../../models/responsable-pago-dispositivo';
import { ResponsablePagoDispositivoData } from '../../models/responsable-pago-dispositivo-data';

export interface ActualizarDispositivoResponsablePagoResponsablesPagoDispositivosDispositivoIdPut$Params {
  dispositivo_id: number;
      body: ResponsablePagoDispositivoData
}

export function actualizarDispositivoResponsablePagoResponsablesPagoDispositivosDispositivoIdPut(http: HttpClient, rootUrl: string, params: ActualizarDispositivoResponsablePagoResponsablesPagoDispositivosDispositivoIdPut$Params, context?: HttpContext): Observable<StrictHttpResponse<ResponsablePagoDispositivo>> {
  const rb = new RequestBuilder(rootUrl, actualizarDispositivoResponsablePagoResponsablesPagoDispositivosDispositivoIdPut.PATH, 'put');
  if (params) {
    rb.path('dispositivo_id', params.dispositivo_id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ResponsablePagoDispositivo>;
    })
  );
}

actualizarDispositivoResponsablePagoResponsablesPagoDispositivosDispositivoIdPut.PATH = '/responsables-pago/dispositivos/{dispositivo_id}';
