/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ResponsablePago } from '../../models/responsable-pago';
import { ResponsablePagoData } from '../../models/responsable-pago-data';

export interface CrearResponsablePagoResponsablesPagoPost$Params {
      body: ResponsablePagoData
}

export function crearResponsablePagoResponsablesPagoPost(http: HttpClient, rootUrl: string, params: CrearResponsablePagoResponsablesPagoPost$Params, context?: HttpContext): Observable<StrictHttpResponse<ResponsablePago>> {
  const rb = new RequestBuilder(rootUrl, crearResponsablePagoResponsablesPagoPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ResponsablePago>;
    })
  );
}

crearResponsablePagoResponsablesPagoPost.PATH = '/responsables-pago/';
