/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Institucion } from '../../models/institucion';
import { InstitucionData } from '../../models/institucion-data';

export interface CrearInstitucionInstitucionesPost$Params {
      body: InstitucionData
}

export function crearInstitucionInstitucionesPost(http: HttpClient, rootUrl: string, params: CrearInstitucionInstitucionesPost$Params, context?: HttpContext): Observable<StrictHttpResponse<Institucion>> {
  const rb = new RequestBuilder(rootUrl, crearInstitucionInstitucionesPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Institucion>;
    })
  );
}

crearInstitucionInstitucionesPost.PATH = '/instituciones/';
