/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Estudiante } from '../../models/estudiante';
import { EstudianteData } from '../../models/estudiante-data';

export interface CrearEstudianteEstudiantesPost$Params {
      body: EstudianteData
}

export function crearEstudianteEstudiantesPost(http: HttpClient, rootUrl: string, params: CrearEstudianteEstudiantesPost$Params, context?: HttpContext): Observable<StrictHttpResponse<Estudiante>> {
  const rb = new RequestBuilder(rootUrl, crearEstudianteEstudiantesPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Estudiante>;
    })
  );
}

crearEstudianteEstudiantesPost.PATH = '/estudiantes/';
