/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface EliminarDispositivoResponsablePagoResponsablesPagoDispositivosDispositivoIdDelete$Params {
  dispositivo_id: number;
}

export function eliminarDispositivoResponsablePagoResponsablesPagoDispositivosDispositivoIdDelete(http: HttpClient, rootUrl: string, params: EliminarDispositivoResponsablePagoResponsablesPagoDispositivosDispositivoIdDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<any>> {
  const rb = new RequestBuilder(rootUrl, eliminarDispositivoResponsablePagoResponsablesPagoDispositivosDispositivoIdDelete.PATH, 'delete');
  if (params) {
    rb.path('dispositivo_id', params.dispositivo_id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<any>;
    })
  );
}

eliminarDispositivoResponsablePagoResponsablesPagoDispositivosDispositivoIdDelete.PATH = '/responsables-pago/dispositivos/{dispositivo_id}';
