/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface EliminarCronogramaCronogramasCronogramaIdDelete$Params {
  cronograma_id: number;
}

export function eliminarCronogramaCronogramasCronogramaIdDelete(http: HttpClient, rootUrl: string, params: EliminarCronogramaCronogramasCronogramaIdDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<any>> {
  const rb = new RequestBuilder(rootUrl, eliminarCronogramaCronogramasCronogramaIdDelete.PATH, 'delete');
  if (params) {
    rb.path('cronograma_id', params.cronograma_id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<any>;
    })
  );
}

eliminarCronogramaCronogramasCronogramaIdDelete.PATH = '/cronogramas/{cronograma_id}';
