/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface EliminarResponsablePagoResponsablesPagoResponsablePagoIdDelete$Params {
  responsable_pago_id: number;
}

export function eliminarResponsablePagoResponsablesPagoResponsablePagoIdDelete(http: HttpClient, rootUrl: string, params: EliminarResponsablePagoResponsablesPagoResponsablePagoIdDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<any>> {
  const rb = new RequestBuilder(rootUrl, eliminarResponsablePagoResponsablesPagoResponsablePagoIdDelete.PATH, 'delete');
  if (params) {
    rb.path('responsable_pago_id', params.responsable_pago_id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<any>;
    })
  );
}

eliminarResponsablePagoResponsablesPagoResponsablePagoIdDelete.PATH = '/responsables-pago/{responsable_pago_id}';
