/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface EliminarInstitucionInstitucionesInstitucionIdDelete$Params {
  institucion_id: number;
}

export function eliminarInstitucionInstitucionesInstitucionIdDelete(http: HttpClient, rootUrl: string, params: EliminarInstitucionInstitucionesInstitucionIdDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<any>> {
  const rb = new RequestBuilder(rootUrl, eliminarInstitucionInstitucionesInstitucionIdDelete.PATH, 'delete');
  if (params) {
    rb.path('institucion_id', params.institucion_id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<any>;
    })
  );
}

eliminarInstitucionInstitucionesInstitucionIdDelete.PATH = '/instituciones/{institucion_id}';
