/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface EliminarEstudianteEstudiantesEstudianteIdDelete$Params {
  estudiante_id: number;
}

export function eliminarEstudianteEstudiantesEstudianteIdDelete(http: HttpClient, rootUrl: string, params: EliminarEstudianteEstudiantesEstudianteIdDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<any>> {
  const rb = new RequestBuilder(rootUrl, eliminarEstudianteEstudiantesEstudianteIdDelete.PATH, 'delete');
  if (params) {
    rb.path('estudiante_id', params.estudiante_id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<any>;
    })
  );
}

eliminarEstudianteEstudiantesEstudianteIdDelete.PATH = '/estudiantes/{estudiante_id}';
