/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PaginationDataResponsablePagoDispositivos } from '../../models/pagination-data-responsable-pago-dispositivos';

export interface ListarDispositivosResponsablePagoResponsablesPagoResponsablePagoIdDispositivosGet$Params {
  responsable_pago_id: number;
  skip?: number;
  limit?: number;
}

export function listarDispositivosResponsablePagoResponsablesPagoResponsablePagoIdDispositivosGet(http: HttpClient, rootUrl: string, params: ListarDispositivosResponsablePagoResponsablesPagoResponsablePagoIdDispositivosGet$Params, context?: HttpContext): Observable<StrictHttpResponse<PaginationDataResponsablePagoDispositivos>> {
  const rb = new RequestBuilder(rootUrl, listarDispositivosResponsablePagoResponsablesPagoResponsablePagoIdDispositivosGet.PATH, 'get');
  if (params) {
    rb.path('responsable_pago_id', params.responsable_pago_id, {});
    rb.query('skip', params.skip, {});
    rb.query('limit', params.limit, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PaginationDataResponsablePagoDispositivos>;
    })
  );
}

listarDispositivosResponsablePagoResponsablesPagoResponsablePagoIdDispositivosGet.PATH = '/responsables-pago/{responsable_pago_id}/dispositivos/';
