/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Cuenta } from '../../models/cuenta';
import { CuentaPatch } from '../../models/cuenta-patch';

export interface ParchearCuentaCuentasCuentaIdPatch$Params {
  cuenta_id: number;
      body: CuentaPatch
}

export function parchearCuentaCuentasCuentaIdPatch(http: HttpClient, rootUrl: string, params: ParchearCuentaCuentasCuentaIdPatch$Params, context?: HttpContext): Observable<StrictHttpResponse<Cuenta>> {
  const rb = new RequestBuilder(rootUrl, parchearCuentaCuentasCuentaIdPatch.PATH, 'patch');
  if (params) {
    rb.path('cuenta_id', params.cuenta_id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Cuenta>;
    })
  );
}

parchearCuentaCuentasCuentaIdPatch.PATH = '/cuentas/{cuenta_id}';
