/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ResponsablePago } from '../../models/responsable-pago';
import { ResponsablePagoPatch } from '../../models/responsable-pago-patch';

export interface ParchearResponsablePagoResponsablesPagoResponsablePagoIdPatch$Params {
  responsable_pago_id: number;
      body: ResponsablePagoPatch
}

export function parchearResponsablePagoResponsablesPagoResponsablePagoIdPatch(http: HttpClient, rootUrl: string, params: ParchearResponsablePagoResponsablesPagoResponsablePagoIdPatch$Params, context?: HttpContext): Observable<StrictHttpResponse<ResponsablePago>> {
  const rb = new RequestBuilder(rootUrl, parchearResponsablePagoResponsablesPagoResponsablePagoIdPatch.PATH, 'patch');
  if (params) {
    rb.path('responsable_pago_id', params.responsable_pago_id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ResponsablePago>;
    })
  );
}

parchearResponsablePagoResponsablesPagoResponsablePagoIdPatch.PATH = '/responsables-pago/{responsable_pago_id}';
