/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Estudiante } from '../../models/estudiante';
import { EstudiantePatch } from '../../models/estudiante-patch';

export interface ParchearEstudianteEstudiantesEstudianteIdPatch$Params {
  estudiante_id: number;
      body: EstudiantePatch
}

export function parchearEstudianteEstudiantesEstudianteIdPatch(http: HttpClient, rootUrl: string, params: ParchearEstudianteEstudiantesEstudianteIdPatch$Params, context?: HttpContext): Observable<StrictHttpResponse<Estudiante>> {
  const rb = new RequestBuilder(rootUrl, parchearEstudianteEstudiantesEstudianteIdPatch.PATH, 'patch');
  if (params) {
    rb.path('estudiante_id', params.estudiante_id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Estudiante>;
    })
  );
}

parchearEstudianteEstudiantesEstudianteIdPatch.PATH = '/estudiantes/{estudiante_id}';
