/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Institucion } from '../../models/institucion';
import { InstitucionPatch } from '../../models/institucion-patch';

export interface ParchearInstitucionInstitucionesInstitucionIdPatch$Params {
  institucion_id: number;
      body: InstitucionPatch
}

export function parchearInstitucionInstitucionesInstitucionIdPatch(http: HttpClient, rootUrl: string, params: ParchearInstitucionInstitucionesInstitucionIdPatch$Params, context?: HttpContext): Observable<StrictHttpResponse<Institucion>> {
  const rb = new RequestBuilder(rootUrl, parchearInstitucionInstitucionesInstitucionIdPatch.PATH, 'patch');
  if (params) {
    rb.path('institucion_id', params.institucion_id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Institucion>;
    })
  );
}

parchearInstitucionInstitucionesInstitucionIdPatch.PATH = '/instituciones/{institucion_id}';
