/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CalendarioPatch {
  fin_vigencia?: (string | null);
  id_estado_cuenta?: (number | null);
  id_riesgo_cliente?: (number | null);
  id_tipo_deuda?: (number | null);
  inicio_vigencia?: (string | null);
}
