/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CalendarioPrograma {
  activo?: boolean;
  actualizado_en?: (string | null);
  antiguedad_final: string;
  antiguedad_inicial: string;
  creado_en?: (string | null);
  id?: (number | null);
  id_calendario: number;
  id_tipo_evento: number;
}
