/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Calendario {
  activo?: boolean;
  actualizado_en?: (string | null);
  creado_en?: (string | null);
  fin_vigencia: string;
  id?: (number | null);
  id_estado_cuenta: number;
  id_riesgo_cliente: number;
  id_tipo_deuda: number;
  inicio_vigencia: string;
}
