/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CalendarioData {
  fin_vigencia: string;
  id_estado_cuenta: number;
  id_riesgo_cliente: number;
  id_tipo_deuda: number;
  inicio_vigencia: string;
}
