/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CampaniaPatch {
  calendario_programa_id?: (number | null);
  canal?: (string | null);
  descripcion?: (string | null);
  horario_fin?: (string | null);
  horario_inicio?: (string | null);
  max_reintentos?: (number | null);
  nombre?: (string | null);
  plantilla_id?: (number | null);
  prioridad?: (number | null);
  template_ivr?: (string | null);
  template_sms?: (string | null);
  template_whatsapp?: (string | null);
}
