/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CampaniaData {
  calendario_programa_id: number;
  canal: string;
  descripcion?: (string | null);
  horario_fin: string;
  horario_inicio: string;
  max_reintentos?: number;
  nombre: string;
  plantilla_id?: (number | null);
  prioridad?: number;
  template_ivr?: (string | null);
  template_sms?: (string | null);
  template_whatsapp?: (string | null);
}
