/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Campania {
  activo?: boolean;
  actualizado_en?: (string | null);
  calendario_programa_id?: (number | null);
  canal: string;
  creado_en?: (string | null);
  descripcion?: (string | null);
  horario_fin: string;
  horario_inicio: string;
  id?: (number | null);
  max_reintentos?: number;
  nombre: string;
  plantilla_id?: (number | null);
  prioridad?: number;
  template_ivr?: (string | null);
  template_sms?: (string | null);
  template_whatsapp?: (string | null);
}
