/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CompromisoExoneracionUpdate {
  activo?: (boolean | null);
  estado?: (string | null);
  fecha_cierre?: (string | null);
  fecha_inicio?: (string | null);
  monto?: (number | null);
  motivo?: (string | null);
  tipo?: (string | null);
}
