/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CompromisoExoneracionResponse {
  activo: boolean;
  cuenta_id: number;
  estado: string;
  fecha_cierre: string;
  fecha_inicio: string;
  id: number;
  monto: number;
  motivo: (string | null);
  recibo_factura_id: number;
  tipo: string;
}
