/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CompromisoExoneracionCreate {
  cuenta_id: number;
  estado?: string;
  fecha_cierre: string;
  fecha_inicio: string;
  monto: number;
  motivo?: (string | null);
  recibo_factura_id: number;
  tipo: string;
}
