/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ConfirmarInstitucionRequest {
  admin_email: string;
  admin_token: string;
  institucion_id: number;
  institucion_token: string;
}
