/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CronogramaPatch {
  codigo_cronograma?: (string | null);
  descripcion?: (string | null);
  institucion_id?: (number | null);
}
