/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Cronograma {
  activo?: boolean;
  actualizado_en?: (string | null);
  codigo_cronograma: string;
  creado_en?: (string | null);
  descripcion: string;
  id?: (number | null);
  institucion_id: number;
}
