/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CuentaPatch {
  cod_cuenta?: (string | null);
  cronograma_id?: (number | null);
  deuda_actual?: (number | null);
  estudiante_id?: (number | null);
  institucion_id?: (number | null);
  perfil_actual?: (string | null);
  score_actual?: (number | null);
  ultima_actualizacion_score?: (string | null);
}
