/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CuentaData {
  cod_cuenta: string;
  cronograma_id: number;
  deuda_actual: number;
  estudiante_id: number;
  institucion_id: number;
  perfil_actual: string;
  score_actual: number;
  ultima_actualizacion_score?: (string | null);
}
