/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Cuenta {
  activo?: boolean;
  actualizado_en?: (string | null);
  cod_cuenta: string;
  creado_en?: (string | null);
  cronograma_id: number;
  deuda_actual: number;
  estudiante_id: number;
  id?: (number | null);
  institucion_id: number;
  perfil_actual: string;
  score_actual: number;
  ultima_actualizacion_score: (string | null);
}
