/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface EstadoCuenta {
  activo?: boolean;
  actualizado_en?: (string | null);
  creado_en?: (string | null);
  descripcion: string;
  id?: (number | null);
  nombre_estado: string;
}
