/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface EstudianteData {
  apellidos: string;
  documento: string;
  fecha_nacimiento: string;
  grado_actual?: (string | null);
  institucion_id: number;
  nivel_actual?: (string | null);
  nombres: string;
  seccion_actual?: (string | null);
  tipo_documento_id: number;
}
