/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Estudiante {
  activo?: boolean;
  actualizado_en?: (string | null);
  apellidos: string;
  creado_en?: (string | null);
  documento: string;
  fecha_nacimiento: string;
  grado_actual: (string | null);
  id?: (number | null);
  institucion_id: number;
  nivel_actual: (string | null);
  nombres: string;
  seccion_actual: (string | null);
  tipo_documento_id: number;
}
