/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface EstudiantePatch {
  apellidos?: (string | null);
  documento?: (string | null);
  fecha_nacimiento?: (string | null);
  grado_actual?: (string | null);
  institucion_id?: (number | null);
  nivel_actual?: (string | null);
  nombres?: (string | null);
  seccion_actual?: (string | null);
  tipo_documento_id?: (number | null);
}
