/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MarcaEspecialResponse } from '../models/marca-especial-response';
export interface EventoDemandaResponse {
  campania_id: number;
  canal: string;
  cuenta_id: number;
  error_detalle?: (string | null);
  estado: string;
  fecha_ejecucion?: (string | null);
  fecha_programada: string;
  historial_evento_id?: (number | null);
  id: number;
  institucion_id: number;
  marca_especial?: (MarcaEspecialResponse | null);
  mensaje_preview?: (string | null);
  notificacion_estado?: (string | null);
  notificacion_id?: (number | null);
  responsable_pago_dispositivo_id?: (number | null);
  responsable_pago_id: number;
  resultado?: (string | null);
  resultado_envio_id?: (number | null);
}
