/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface EventoDemandaCreate {
  campania_id: number;
  canal: string;
  cuenta_id: number;
  fecha_programada: string;
  institucion_id: number;
  marca_especial_id?: (number | null);
  max_reintentos?: number;
  mensaje_preview?: (string | null);
  prioridad?: number;
  responsable_pago_dispositivo_id?: (number | null);
  responsable_pago_id: number;
}
