/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface FechasFeriados {
  activo?: boolean;
  actualizado_en?: (string | null);
  creado_en?: (string | null);
  descripcion: string;
  fecha: string;
  id?: (number | null);
}
