/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface HistorialEventos {
  activo?: boolean;
  actualizado_en?: (string | null);
  campania_id?: (number | null);
  canal?: (string | null);
  creado_en?: (string | null);
  detalle_error?: (string | null);
  estado_envio?: (string | null);
  fecha_envio: string;
  id?: (number | null);
  id_calendario_programa?: (number | null);
  id_cuenta: number;
  id_resultado_envio: number;
  metadata_payload?: (string | null);
  notificacion_id?: (number | null);
  offset: (number | null);
  proveedor_sid?: (string | null);
  responsable_pago_id?: (number | null);
}
