/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface HistorialEventosPatch {
  campania_id?: (number | null);
  canal?: (string | null);
  detalle_error?: (string | null);
  estado_envio?: (string | null);
  fecha_envio?: (string | null);
  id_calendario_programa?: (number | null);
  id_cuenta?: (number | null);
  id_resultado_envio?: (number | null);
  metadata_payload?: (string | null);
  notificacion_id?: (number | null);
  offset?: (number | null);
  proveedor_sid?: (string | null);
  responsable_pago_id?: (number | null);
}
