/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Modelo que representa las etapas 1 y 2 del proceso (estado/token).
 */
export interface Institucion {
  activo?: boolean;
  actualizado_en?: (string | null);
  creado_en?: (string | null);
  direccion: string;
  estado_registro?: string;
  id?: (number | null);
  nombre: string;
  plan: string;
  telefono: string;
  token_registro_hash?: (string | null);
}
