/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface InstitucionPatch {
  direccion?: (string | null);
  nombre?: (string | null);
  plan?: (string | null);
  telefono?: (string | null);
}
