/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MarcaEspecialUpdate {
  activo?: (boolean | null);
  color_hex?: (string | null);
  descripcion?: (string | null);
  nombre?: (string | null);
}
