/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MarcaEspecialResponse {
  activo: boolean;
  color_hex?: (string | null);
  descripcion?: (string | null);
  id: number;
  institucion_id: number;
  nombre: string;
}
