/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MarcaEspecialCreate {
  color_hex?: (string | null);
  descripcion?: (string | null);
  institucion_id: number;
  nombre: string;
}
