/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface NotificacionPatch {
  campania_id?: (number | null);
  canal?: (string | null);
  cuenta_id?: (number | null);
  estado_envio?: (string | null);
  fecha_envio?: (string | null);
  fecha_programada?: (string | null);
  max_reintentos?: (number | null);
  prioridad?: (number | null);
  proveedor_sid?: (string | null);
  reintentos_realizados?: (number | null);
  responsable_pago_dispositivo_id?: (number | null);
  responsable_pago_id?: (number | null);
  template_usado?: (string | null);
  ultimo_error?: (string | null);
}
