/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface NotificacionData {
  campania_id: number;
  canal: string;
  cuenta_id: number;
  estado_envio?: string;
  fecha_envio?: (string | null);
  fecha_programada: string;
  max_reintentos?: number;
  prioridad: number;
  proveedor_sid?: (string | null);
  reintentos_realizados?: number;
  responsable_pago_dispositivo_id?: (number | null);
  responsable_pago_id: number;
  template_usado?: (string | null);
  ultimo_error?: (string | null);
}
