/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PaginationData } from '../models/pagination-data';
import { PlantillaMensaje } from '../models/plantilla-mensaje';
export interface PaginationDataPlantillasMensaje {
  pagination: PaginationData;
  plantillas: Array<PlantillaMensaje>;
}
