/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Campania } from '../models/campania';
import { PaginationData } from '../models/pagination-data';
export interface PaginationDataCampanias {
  campanias: Array<Campania>;
  pagination: PaginationData;
}
