/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PaginationData } from '../models/pagination-data';
import { Perfil } from '../models/perfil';
export interface PaginationDataPerfiles {
  pagination: PaginationData;
  perfiles: Array<Perfil>;
}
