/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PaginationData } from '../models/pagination-data';
import { ResultadoEnvio } from '../models/resultado-envio';
export interface PaginationDataResultadosEnvio {
  pagination: PaginationData;
  resultados_envio: Array<ResultadoEnvio>;
}
