/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FechasFeriados } from '../models/fechas-feriados';
import { PaginationData } from '../models/pagination-data';
export interface PaginationDataFechasFeriados {
  fechas_feriados: Array<FechasFeriados>;
  pagination: PaginationData;
}
