/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PaginationData } from '../models/pagination-data';
import { ResponsablePagoDispositivo } from '../models/responsable-pago-dispositivo';
export interface PaginationDataResponsablePagoDispositivos {
  dispositivos: Array<ResponsablePagoDispositivo>;
  pagination: PaginationData;
}
