/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HistorialEventos } from '../models/historial-eventos';
import { PaginationData } from '../models/pagination-data';
export interface PaginationDataHistorialEventos {
  historiales_eventos: Array<HistorialEventos>;
  pagination: PaginationData;
}
