/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PaginationData } from '../models/pagination-data';
import { Variable } from '../models/variable';
export interface PaginationDataVariables {
  pagination: PaginationData;
  variables: Array<Variable>;
}
