/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PaginationData } from '../models/pagination-data';
import { TipoEvento } from '../models/tipo-evento';
export interface PaginationDataTiposEvento {
  pagination: PaginationData;
  tipos_evento: Array<TipoEvento>;
}
