/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Cronograma } from '../models/cronograma';
import { PaginationData } from '../models/pagination-data';
export interface PaginationDataCronogramas {
  cronogramas: Array<Cronograma>;
  pagination: PaginationData;
}
