/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Cuenta } from '../models/cuenta';
import { PaginationData } from '../models/pagination-data';
export interface PaginationDataCuentas {
  cuentas: Array<Cuenta>;
  pagination: PaginationData;
}
