/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PaginationData } from '../models/pagination-data';
import { TipoEnvio } from '../models/tipo-envio';
export interface PaginationDataTiposEnvio {
  pagination: PaginationData;
  tipos_envio: Array<TipoEnvio>;
}
