/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PaginationData } from '../models/pagination-data';
import { TipoDeuda } from '../models/tipo-deuda';
export interface PaginationDataTiposDeuda {
  pagination: PaginationData;
  tipos_deuda: Array<TipoDeuda>;
}
