/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Estudiante } from '../models/estudiante';
import { PaginationData } from '../models/pagination-data';
export interface PaginationDataEstudiantes {
  estudiantes: Array<Estudiante>;
  pagination: PaginationData;
}
