/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PaginationData } from '../models/pagination-data';
import { RiesgoCliente } from '../models/riesgo-cliente';
export interface PaginationDataRiesgosCliente {
  pagination: PaginationData;
  riesgos_cliente: Array<RiesgoCliente>;
}
