/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EstadoCuenta } from '../models/estado-cuenta';
import { PaginationData } from '../models/pagination-data';
export interface PaginationDataEstadosCuenta {
  estados_cuenta: Array<EstadoCuenta>;
  pagination: PaginationData;
}
