/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PaginationData } from '../models/pagination-data';
import { ScoringLogData } from '../models/scoring-log-data';
export interface PaginationDataScroringLogs {
  pagination: PaginationData;
  scoring_logs: Array<ScoringLogData>;
}
