/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Notificacion } from '../models/notificacion';
import { PaginationData } from '../models/pagination-data';
export interface PaginationDataNotificaciones {
  notificaciones: Array<Notificacion>;
  pagination: PaginationData;
}
