/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Calendario } from '../models/calendario';
import { PaginationData } from '../models/pagination-data';
export interface PaginationDataCalendarios {
  calendarios: Array<Calendario>;
  pagination: PaginationData;
}
