/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CalendarioPrograma } from '../models/calendario-programa';
import { PaginationData } from '../models/pagination-data';
export interface PaginationDataCalendariosPrograma {
  calendarios_programa: Array<CalendarioPrograma>;
  pagination: PaginationData;
}
