/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PaginationData } from '../models/pagination-data';
import { ResponsablePago } from '../models/responsable-pago';
export interface PaginationDataResponsablesPago {
  pagination: PaginationData;
  responsables_pago: Array<ResponsablePago>;
}
