/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Institucion } from '../models/institucion';
import { PaginationData } from '../models/pagination-data';
export interface PaginationDataInstituciones {
  instituciones: Array<Institucion>;
  pagination: PaginationData;
}
