/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PerfilPatch {
  descripcion?: (string | null);
  max_score?: (number | null);
  min_score?: (number | null);
  nombre?: (string | null);
}
