/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PerfilData {
  descripcion?: (string | null);
  max_score?: number;
  min_score?: number;
  nombre: string;
}
