/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Perfil {
  activo?: boolean;
  actualizado_en?: (string | null);
  creado_en?: (string | null);
  descripcion?: (string | null);
  id?: (number | null);
  max_score: number;
  min_score: number;
  nombre: string;
}
