/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PlantillaMensajePatch {
  aprobado_por?: (string | null);
  canal?: (string | null);
  contenido?: (string | null);
  es_ultima_version?: (boolean | null);
  estado_aprobacion?: (string | null);
  fecha_aprobacion?: (string | null);
  idioma?: (string | null);
  ivr_voice?: (string | null);
  nombre?: (string | null);
  notas?: (string | null);
  twilio_template_sid?: (string | null);
  twilio_whatsapp_namespace?: (string | null);
  variables_disponibles?: (string | null);
  version?: (number | null);
}
