/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PlantillaMensaje {
  activo?: boolean;
  actualizado_en?: (string | null);
  aprobado_por?: (string | null);
  canal: string;
  contenido: string;
  creado_en?: (string | null);
  es_ultima_version?: boolean;
  estado_aprobacion?: string;
  fecha_aprobacion?: (string | null);
  id?: (number | null);
  idioma?: (string | null);
  ivr_voice?: (string | null);
  nombre: string;
  notas?: (string | null);
  twilio_template_sid?: (string | null);
  twilio_whatsapp_namespace?: (string | null);
  variables_disponibles?: (string | null);
  version?: number;
}
