/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RegistroInstitucionRequest {
  admin_email: string;
  admin_nombre?: (string | null);
  admin_password: string;
  institucion_direccion: string;
  institucion_nombre: string;
  institucion_telefono: string;
  plan: string;
}
