/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ReporteFinancieroResponse {
  compromisos_activos: number;
  exoneraciones_activas: number;
  monto_compromisos: number;
  monto_exonerado: number;
  monto_facturado: number;
  monto_pagado: number;
  total_cuentas: number;
  total_pagos: number;
  total_recibos: number;
}
