/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ReporteFinancieroFiltros {
  fecha_fin?: (string | null);
  fecha_inicio?: (string | null);
  formato?: 'json' | 'csv';
  institucion_id?: (number | null);
}
