/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ResponsablePago {
  activo?: boolean;
  actualizado_en?: (string | null);
  apellido: string;
  canal_preferido?: (string | null);
  creado_en?: (string | null);
  direccion?: (string | null);
  documento: string;
  email?: (string | null);
  franja_fin?: (string | null);
  franja_inicio?: (string | null);
  id?: (number | null);
  idioma_preferido?: (string | null);
  institucion_id: number;
  nombre: string;
  numero_principal_verificado?: boolean;
  opt_in_ivr?: boolean;
  opt_in_sms?: boolean;
  opt_in_whatsapp?: boolean;
  telefono?: (string | null);
  tipo_documento_id: number;
}
