/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ResponsablePagoDispositivoPatch {
  alias?: (string | null);
  canal?: (string | null);
  es_principal?: (boolean | null);
  fecha_verificacion?: (string | null);
  numero?: (string | null);
  responsable_pago_id?: (number | null);
  verificado?: (boolean | null);
}
