/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ResponsablePagoDispositivo {
  activo?: boolean;
  actualizado_en?: (string | null);
  alias?: (string | null);
  canal: string;
  creado_en?: (string | null);
  es_principal?: boolean;
  fecha_verificacion?: (string | null);
  id?: (number | null);
  numero: string;
  responsable_pago_id: number;
  verificado?: boolean;
}
