/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ResponsablePagoPatch {
  apellido?: (string | null);
  canal_preferido?: (string | null);
  direccion?: (string | null);
  documento?: (string | null);
  email?: (string | null);
  franja_fin?: (string | null);
  franja_inicio?: (string | null);
  idioma_preferido?: (string | null);
  institucion_id?: (number | null);
  nombre?: (string | null);
  numero_principal_verificado?: (boolean | null);
  opt_in_ivr?: (boolean | null);
  opt_in_sms?: (boolean | null);
  opt_in_whatsapp?: (boolean | null);
  telefono?: (string | null);
  tipo_documento_id?: (number | null);
}
