/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ResponsablePagoDispositivoData {
  alias?: (string | null);
  canal: string;
  es_principal?: boolean;
  fecha_verificacion?: (string | null);
  numero: string;
  responsable_pago_id: number;
  verificado?: boolean;
}
