/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TipoEventoPatch {
  descripcion?: (string | null);
  template?: (string | null);
  tipo_envio_id?: (number | null);
}
