/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TipoEvento {
  activo?: boolean;
  actualizado_en?: (string | null);
  creado_en?: (string | null);
  descripcion: string;
  id?: (number | null);
  template: string;
  tipo_envio_id: number;
}
