/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { VariableType } from '../models/variable-type';
export interface VariableData {
  descripcion?: (string | null);
  nombre: string;
  tipo?: VariableType;
}
