/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { VariableType } from '../models/variable-type';
export interface Variable {
  activo?: boolean;
  actualizado_en?: (string | null);
  creado_en?: (string | null);
  descripcion?: (string | null);
  id?: (number | null);
  nombre: string;
  tipo: VariableType;
}
