/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { VariableType } from '../models/variable-type';
export interface VariablePatch {
  descripcion?: (string | null);
  nombre?: (string | null);
  tipo?: (VariableType | null);
}
