/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { VariableType } from './variable-type';

/**
 * Each possible value of `VariableType`
 */
export const VARIABLE_TYPE: VariableType[] = [
  1,
  2,
  3
];