/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface VincularOAuthRequest {
  access_token: string;
  email: string;
  expires_in?: (number | null);
  external_id: string;
  provider: string;
  refresh_token?: (string | null);
  scope?: (string | null);
}
