/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Calendario } from '../../models/calendario';
import { CalendarioData } from '../../models/calendario-data';

export interface ActualizarCalendarioCalendariosCalendarioIdPut$Params {
  calendario_id: number;
      body: CalendarioData
}

export function actualizarCalendarioCalendariosCalendarioIdPut(http: HttpClient, rootUrl: string, params: ActualizarCalendarioCalendariosCalendarioIdPut$Params, context?: HttpContext): Observable<StrictHttpResponse<Calendario>> {
  const rb = new RequestBuilder(rootUrl, actualizarCalendarioCalendariosCalendarioIdPut.PATH, 'put');
  if (params) {
    rb.path('calendario_id', params.calendario_id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Calendario>;
    })
  );
}

actualizarCalendarioCalendariosCalendarioIdPut.PATH = '/calendarios/{calendario_id}';
