/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TipoEnvio } from '../../models/tipo-envio';
import { TipoEnvioData } from '../../models/tipo-envio-data';

export interface ActualizarTipoEnvioTiposEnvioTipoEnvioIdPut$Params {
  tipo_envio_id: number;
      body: TipoEnvioData
}

export function actualizarTipoEnvioTiposEnvioTipoEnvioIdPut(http: HttpClient, rootUrl: string, params: ActualizarTipoEnvioTiposEnvioTipoEnvioIdPut$Params, context?: HttpContext): Observable<StrictHttpResponse<TipoEnvio>> {
  const rb = new RequestBuilder(rootUrl, actualizarTipoEnvioTiposEnvioTipoEnvioIdPut.PATH, 'put');
  if (params) {
    rb.path('tipo_envio_id', params.tipo_envio_id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TipoEnvio>;
    })
  );
}

actualizarTipoEnvioTiposEnvioTipoEnvioIdPut.PATH = '/tipos-envio/{tipo_envio_id}';
