/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TipoEvento } from '../../models/tipo-evento';
import { TipoEventoData } from '../../models/tipo-evento-data';

export interface ActualizarTipoEventoTiposEventoTipoEventoIdPut$Params {
  tipo_evento_id: number;
      body: TipoEventoData
}

export function actualizarTipoEventoTiposEventoTipoEventoIdPut(http: HttpClient, rootUrl: string, params: ActualizarTipoEventoTiposEventoTipoEventoIdPut$Params, context?: HttpContext): Observable<StrictHttpResponse<TipoEvento>> {
  const rb = new RequestBuilder(rootUrl, actualizarTipoEventoTiposEventoTipoEventoIdPut.PATH, 'put');
  if (params) {
    rb.path('tipo_evento_id', params.tipo_evento_id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TipoEvento>;
    })
  );
}

actualizarTipoEventoTiposEventoTipoEventoIdPut.PATH = '/tipos-evento/{tipo_evento_id}';
