/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TipoDeuda } from '../../models/tipo-deuda';
import { TipoDeudaData } from '../../models/tipo-deuda-data';

export interface ActualizarTipoDeudaTiposDeudaTipoDeudaIdPut$Params {
  tipo_deuda_id: number;
      body: TipoDeudaData
}

export function actualizarTipoDeudaTiposDeudaTipoDeudaIdPut(http: HttpClient, rootUrl: string, params: ActualizarTipoDeudaTiposDeudaTipoDeudaIdPut$Params, context?: HttpContext): Observable<StrictHttpResponse<TipoDeuda>> {
  const rb = new RequestBuilder(rootUrl, actualizarTipoDeudaTiposDeudaTipoDeudaIdPut.PATH, 'put');
  if (params) {
    rb.path('tipo_deuda_id', params.tipo_deuda_id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TipoDeuda>;
    })
  );
}

actualizarTipoDeudaTiposDeudaTipoDeudaIdPut.PATH = '/tipos-deuda/{tipo_deuda_id}';
