/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FechasFeriados } from '../../models/fechas-feriados';
import { FechasFeriadosData } from '../../models/fechas-feriados-data';

export interface ActualizarFechaFeriadaFechasFeriadasFechaFeriadaIdPut$Params {
  fecha_feriada_id: number;
      body: FechasFeriadosData
}

export function actualizarFechaFeriadaFechasFeriadasFechaFeriadaIdPut(http: HttpClient, rootUrl: string, params: ActualizarFechaFeriadaFechasFeriadasFechaFeriadaIdPut$Params, context?: HttpContext): Observable<StrictHttpResponse<FechasFeriados>> {
  const rb = new RequestBuilder(rootUrl, actualizarFechaFeriadaFechasFeriadasFechaFeriadaIdPut.PATH, 'put');
  if (params) {
    rb.path('fecha_feriada_id', params.fecha_feriada_id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<FechasFeriados>;
    })
  );
}

actualizarFechaFeriadaFechasFeriadasFechaFeriadaIdPut.PATH = '/fechas-feriadas/{fecha_feriada_id}';
