/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FechasFeriados } from '../../models/fechas-feriados';
import { FechasFeriadosData } from '../../models/fechas-feriados-data';

export interface CrearFechaFeriadaFechasFeriadasPost$Params {
      body: FechasFeriadosData
}

export function crearFechaFeriadaFechasFeriadasPost(http: HttpClient, rootUrl: string, params: CrearFechaFeriadaFechasFeriadasPost$Params, context?: HttpContext): Observable<StrictHttpResponse<FechasFeriados>> {
  const rb = new RequestBuilder(rootUrl, crearFechaFeriadaFechasFeriadasPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<FechasFeriados>;
    })
  );
}

crearFechaFeriadaFechasFeriadasPost.PATH = '/fechas-feriadas/';
