/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TipoEvento } from '../../models/tipo-evento';
import { TipoEventoData } from '../../models/tipo-evento-data';

export interface CrearTipoEventoTiposEventoPost$Params {
      body: TipoEventoData
}

export function crearTipoEventoTiposEventoPost(http: HttpClient, rootUrl: string, params: CrearTipoEventoTiposEventoPost$Params, context?: HttpContext): Observable<StrictHttpResponse<TipoEvento>> {
  const rb = new RequestBuilder(rootUrl, crearTipoEventoTiposEventoPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TipoEvento>;
    })
  );
}

crearTipoEventoTiposEventoPost.PATH = '/tipos-evento/';
