/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TipoEnvio } from '../../models/tipo-envio';
import { TipoEnvioData } from '../../models/tipo-envio-data';

export interface CrearTipoEnvioTiposEnvioPost$Params {
      body: TipoEnvioData
}

export function crearTipoEnvioTiposEnvioPost(http: HttpClient, rootUrl: string, params: CrearTipoEnvioTiposEnvioPost$Params, context?: HttpContext): Observable<StrictHttpResponse<TipoEnvio>> {
  const rb = new RequestBuilder(rootUrl, crearTipoEnvioTiposEnvioPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TipoEnvio>;
    })
  );
}

crearTipoEnvioTiposEnvioPost.PATH = '/tipos-envio/';
