/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RiesgoCliente } from '../../models/riesgo-cliente';
import { RiesgoClienteData } from '../../models/riesgo-cliente-data';

export interface CrearRiesgoClienteRiesgosClientePost$Params {
      body: RiesgoClienteData
}

export function crearRiesgoClienteRiesgosClientePost(http: HttpClient, rootUrl: string, params: CrearRiesgoClienteRiesgosClientePost$Params, context?: HttpContext): Observable<StrictHttpResponse<RiesgoCliente>> {
  const rb = new RequestBuilder(rootUrl, crearRiesgoClienteRiesgosClientePost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<RiesgoCliente>;
    })
  );
}

crearRiesgoClienteRiesgosClientePost.PATH = '/riesgos-cliente/';
