/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TipoDeuda } from '../../models/tipo-deuda';
import { TipoDeudaData } from '../../models/tipo-deuda-data';

export interface CrearTipoDeudaTiposDeudaPost$Params {
      body: TipoDeudaData
}

export function crearTipoDeudaTiposDeudaPost(http: HttpClient, rootUrl: string, params: CrearTipoDeudaTiposDeudaPost$Params, context?: HttpContext): Observable<StrictHttpResponse<TipoDeuda>> {
  const rb = new RequestBuilder(rootUrl, crearTipoDeudaTiposDeudaPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TipoDeuda>;
    })
  );
}

crearTipoDeudaTiposDeudaPost.PATH = '/tipos-deuda/';
