/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ResultadoEnvio } from '../../models/resultado-envio';
import { ResultadoEnvioData } from '../../models/resultado-envio-data';

export interface CrearResultadoEnvioResultadosEnvioPost$Params {
      body: ResultadoEnvioData
}

export function crearResultadoEnvioResultadosEnvioPost(http: HttpClient, rootUrl: string, params: CrearResultadoEnvioResultadosEnvioPost$Params, context?: HttpContext): Observable<StrictHttpResponse<ResultadoEnvio>> {
  const rb = new RequestBuilder(rootUrl, crearResultadoEnvioResultadosEnvioPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ResultadoEnvio>;
    })
  );
}

crearResultadoEnvioResultadosEnvioPost.PATH = '/resultados-envio/';
