/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { HistorialEventos } from '../../models/historial-eventos';
import { HistorialEventosData } from '../../models/historial-eventos-data';

export interface CrearHistorialEventoHistorialesEventosPost$Params {
      body: HistorialEventosData
}

export function crearHistorialEventoHistorialesEventosPost(http: HttpClient, rootUrl: string, params: CrearHistorialEventoHistorialesEventosPost$Params, context?: HttpContext): Observable<StrictHttpResponse<HistorialEventos>> {
  const rb = new RequestBuilder(rootUrl, crearHistorialEventoHistorialesEventosPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<HistorialEventos>;
    })
  );
}

crearHistorialEventoHistorialesEventosPost.PATH = '/historiales-eventos/';
