/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface EliminarFechaFeriadaFechasFeriadasFechaFeriadaIdDelete$Params {
  fecha_feriada_id: number;
}

export function eliminarFechaFeriadaFechasFeriadasFechaFeriadaIdDelete(http: HttpClient, rootUrl: string, params: EliminarFechaFeriadaFechasFeriadasFechaFeriadaIdDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<any>> {
  const rb = new RequestBuilder(rootUrl, eliminarFechaFeriadaFechasFeriadasFechaFeriadaIdDelete.PATH, 'delete');
  if (params) {
    rb.path('fecha_feriada_id', params.fecha_feriada_id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<any>;
    })
  );
}

eliminarFechaFeriadaFechasFeriadasFechaFeriadaIdDelete.PATH = '/fechas-feriadas/{fecha_feriada_id}';
