/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface EliminarHistorialEventoHistorialesEventosHistorialEventoIdDelete$Params {
  historial_evento_id: number;
}

export function eliminarHistorialEventoHistorialesEventosHistorialEventoIdDelete(http: HttpClient, rootUrl: string, params: EliminarHistorialEventoHistorialesEventosHistorialEventoIdDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<any>> {
  const rb = new RequestBuilder(rootUrl, eliminarHistorialEventoHistorialesEventosHistorialEventoIdDelete.PATH, 'delete');
  if (params) {
    rb.path('historial_evento_id', params.historial_evento_id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<any>;
    })
  );
}

eliminarHistorialEventoHistorialesEventosHistorialEventoIdDelete.PATH = '/historiales-eventos/{historial_evento_id}';
