/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface EliminarEstadoCuentaEstadosCuentaEstadoCuentaIdDelete$Params {
  estado_cuenta_id: number;
}

export function eliminarEstadoCuentaEstadosCuentaEstadoCuentaIdDelete(http: HttpClient, rootUrl: string, params: EliminarEstadoCuentaEstadosCuentaEstadoCuentaIdDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<any>> {
  const rb = new RequestBuilder(rootUrl, eliminarEstadoCuentaEstadosCuentaEstadoCuentaIdDelete.PATH, 'delete');
  if (params) {
    rb.path('estado_cuenta_id', params.estado_cuenta_id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<any>;
    })
  );
}

eliminarEstadoCuentaEstadosCuentaEstadoCuentaIdDelete.PATH = '/estados-cuenta/{estado_cuenta_id}';
