/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface EliminarResultadoEnvioResultadosEnvioResultadoEnvioIdDelete$Params {
  resultado_envio_id: number;
}

export function eliminarResultadoEnvioResultadosEnvioResultadoEnvioIdDelete(http: HttpClient, rootUrl: string, params: EliminarResultadoEnvioResultadosEnvioResultadoEnvioIdDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<any>> {
  const rb = new RequestBuilder(rootUrl, eliminarResultadoEnvioResultadosEnvioResultadoEnvioIdDelete.PATH, 'delete');
  if (params) {
    rb.path('resultado_envio_id', params.resultado_envio_id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<any>;
    })
  );
}

eliminarResultadoEnvioResultadosEnvioResultadoEnvioIdDelete.PATH = '/resultados-envio/{resultado_envio_id}';
