/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface EliminarTipoDeudaTiposDeudaTipoDeudaIdDelete$Params {
  tipo_deuda_id: number;
}

export function eliminarTipoDeudaTiposDeudaTipoDeudaIdDelete(http: HttpClient, rootUrl: string, params: EliminarTipoDeudaTiposDeudaTipoDeudaIdDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<any>> {
  const rb = new RequestBuilder(rootUrl, eliminarTipoDeudaTiposDeudaTipoDeudaIdDelete.PATH, 'delete');
  if (params) {
    rb.path('tipo_deuda_id', params.tipo_deuda_id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<any>;
    })
  );
}

eliminarTipoDeudaTiposDeudaTipoDeudaIdDelete.PATH = '/tipos-deuda/{tipo_deuda_id}';
