/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PaginationDataHistorialEventos } from '../../models/pagination-data-historial-eventos';

export interface ListarHistorialesEventosHistorialesEventosGet$Params {
  skip?: number;
  limit?: number;
}

export function listarHistorialesEventosHistorialesEventosGet(http: HttpClient, rootUrl: string, params?: ListarHistorialesEventosHistorialesEventosGet$Params, context?: HttpContext): Observable<StrictHttpResponse<PaginationDataHistorialEventos>> {
  const rb = new RequestBuilder(rootUrl, listarHistorialesEventosHistorialesEventosGet.PATH, 'get');
  if (params) {
    rb.query('skip', params.skip, {});
    rb.query('limit', params.limit, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PaginationDataHistorialEventos>;
    })
  );
}

listarHistorialesEventosHistorialesEventosGet.PATH = '/historiales-eventos/';
