/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ResultadoEnvio } from '../../models/resultado-envio';
import { ResultadoEnvioPatch } from '../../models/resultado-envio-patch';

export interface ParchearResultadoEnvioResultadosEnvioResultadoEnvioIdPatch$Params {
  resultado_envio_id: number;
      body: ResultadoEnvioPatch
}

export function parchearResultadoEnvioResultadosEnvioResultadoEnvioIdPatch(http: HttpClient, rootUrl: string, params: ParchearResultadoEnvioResultadosEnvioResultadoEnvioIdPatch$Params, context?: HttpContext): Observable<StrictHttpResponse<ResultadoEnvio>> {
  const rb = new RequestBuilder(rootUrl, parchearResultadoEnvioResultadosEnvioResultadoEnvioIdPatch.PATH, 'patch');
  if (params) {
    rb.path('resultado_envio_id', params.resultado_envio_id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ResultadoEnvio>;
    })
  );
}

parchearResultadoEnvioResultadosEnvioResultadoEnvioIdPatch.PATH = '/resultados-envio/{resultado_envio_id}';
