/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { HistorialEventos } from '../../models/historial-eventos';
import { HistorialEventosPatch } from '../../models/historial-eventos-patch';

export interface ParchearHistorialEventoHistorialesEventosHistorialEventoIdPatch$Params {
  historial_evento_id: number;
      body: HistorialEventosPatch
}

export function parchearHistorialEventoHistorialesEventosHistorialEventoIdPatch(http: HttpClient, rootUrl: string, params: ParchearHistorialEventoHistorialesEventosHistorialEventoIdPatch$Params, context?: HttpContext): Observable<StrictHttpResponse<HistorialEventos>> {
  const rb = new RequestBuilder(rootUrl, parchearHistorialEventoHistorialesEventosHistorialEventoIdPatch.PATH, 'patch');
  if (params) {
    rb.path('historial_evento_id', params.historial_evento_id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<HistorialEventos>;
    })
  );
}

parchearHistorialEventoHistorialesEventosHistorialEventoIdPatch.PATH = '/historiales-eventos/{historial_evento_id}';
