/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { EstadoCuenta } from '../../models/estado-cuenta';
import { EstadoCuentaPatch } from '../../models/estado-cuenta-patch';

export interface ParchearEstadoCuentaEstadosCuentaEstadoCuentaIdPatch$Params {
  estado_cuenta_id: number;
      body: EstadoCuentaPatch
}

export function parchearEstadoCuentaEstadosCuentaEstadoCuentaIdPatch(http: HttpClient, rootUrl: string, params: ParchearEstadoCuentaEstadosCuentaEstadoCuentaIdPatch$Params, context?: HttpContext): Observable<StrictHttpResponse<EstadoCuenta>> {
  const rb = new RequestBuilder(rootUrl, parchearEstadoCuentaEstadosCuentaEstadoCuentaIdPatch.PATH, 'patch');
  if (params) {
    rb.path('estado_cuenta_id', params.estado_cuenta_id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<EstadoCuenta>;
    })
  );
}

parchearEstadoCuentaEstadosCuentaEstadoCuentaIdPatch.PATH = '/estados-cuenta/{estado_cuenta_id}';
