/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseInstitutionResponse } from '../../models/api-response-institution-response';
import { InstitutionUpdateLdpa } from '../../models/institution-update-ldpa';

export interface ActualizarConfiguracionLdapDeInstitucion$Params {
  id: number;
      body: InstitutionUpdateLdpa
}

export function actualizarConfiguracionLdapDeInstitucion(http: HttpClient, rootUrl: string, params: ActualizarConfiguracionLdapDeInstitucion$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseInstitutionResponse>> {
  const rb = new RequestBuilder(rootUrl, actualizarConfiguracionLdapDeInstitucion.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseInstitutionResponse>;
    })
  );
}

actualizarConfiguracionLdapDeInstitucion.PATH = '/institutions/{id}/ldap';
