/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseInstitutionResponse } from '../../models/api-response-institution-response';
import { InstitutionPlanUpdateRequest } from '../../models/institution-plan-update-request';

export interface ActualizarPlan$Params {
  id: number;
      body: InstitutionPlanUpdateRequest
}

export function actualizarPlan(http: HttpClient, rootUrl: string, params: ActualizarPlan$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseInstitutionResponse>> {
  const rb = new RequestBuilder(rootUrl, actualizarPlan.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseInstitutionResponse>;
    })
  );
}

actualizarPlan.PATH = '/institutions/{id}/plan';
