/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseInstitutionResponse } from '../../models/api-response-institution-response';

export interface GetByCode$Params {
  institutionCode: string;
}

export function getByCode(http: HttpClient, rootUrl: string, params: GetByCode$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseInstitutionResponse>> {
  const rb = new RequestBuilder(rootUrl, getByCode.PATH, 'get');
  if (params) {
    rb.path('institutionCode', params.institutionCode, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseInstitutionResponse>;
    })
  );
}

getByCode.PATH = '/institutions/code/{institutionCode}';
